name: CI/CD - ms_notification_email

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run tests (pytest)
    runs-on: ubuntu-latest

    # Environment variables only testing (dummy values)
    env:
      SMTP_SERVER: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: test_user
      SMTP_PASSWORD: test_password
      SENDER_EMAIL: noreply@example.com
      RABBITMQ_URL: amqp://guest:guest@localhost/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

  build_and_push_develop:
    name: Build & Push Docker (:develop)
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (tag develop)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms-notification-email:develop

  build_and_push_main:
    name: Build & Push Docker (:latest)
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (tag latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms-notification-email:latest
